#include "cli_help.h"
#include "args.h"

#include <stdio.h>

void print_help(const char *prog) {
  write_parts(stdout, (const char *[]){"usage: ", prog, " [options]\n\n"}, 3);
  fputs(
    "  -a, --aquatic-life <def> comma-separated, default: all on, fish=auto\n"
    "                             fish=<N|auto>,ducks,dolphins,ship,swan,kaiju,crab,shark,\n"
    "                             submarine,whale,jellyfish,monster,bigfish,swordfish,\n"
    "                             seahorse,rowers,sailboat,fishhook,turtle\n"
    "  -c, --classic [1.0|1.1]    classic mode, conflicts: -a -f -u -m -M -P -n\n"
    "  -m, --message <text>       bg text/ascii art ('-' for stdin)\n"
    "  -M, --message-color <c>    -m text color (default: blue)\n"
    "                             red,green,blue,yellow,magenta,cyan,white,black\n"
    "                             capitalized first letter=bold\n"
    "  -P, --message-position <p> -m placement\n"
    "                             middle: horizontally+vertically centered (default)\n"
    "                             center: horizontally centered, vertical top\n"
    "                             marquee: centered scrolling\n"
    "                             swim: top row, scrolls right to left\n"
    "                             event: like swim, but random\n"
    "  -p, --pace <pace>          speed multiplier, 0.01-10 (default: 1)\n"
    "  -u, --uturn-chance <N>     fish turn per N ticks (default: 400, 0 = never)\n"
    "  -C, --colors <num|name>    foreground colors (default: 16)\n"
    "                             1|2 also take a -<color> suffix, e.g. 2-green\n"
    "                             4: RGBW, 7: teletext, 8: also takes 8-bold\n"
    "  -f, --fps <N>              render frames per second, 1-240 (default: 24)\n"
    "  -s, --screensaver          exit on any keypress\n"
    "  -t, --transparent          transparent background (default: opaque black)\n"
    "      --teletext <t42|ts>    binary teletext stream to stdout instead of the terminal\n"
    "                             t42: raw 42-byte packets, ts: MPEG-TS with teletext PES\n"
    "      --teletext-mode <mode> \"text\": 39 columns, exact ASCII via X/26\n"
    "                             \"mosaic\": 2x3 blocks, 78 columns (default: text)\n"
    "      --mcast <IP:PORT>      send MPEG-TS teletext to a multicast group, [GROUP]:PORT for IPv6\n"
    "      --ttl <N>              multicast TTL/hops, 1-255 (default: 1)\n"
    "      --iface <if>           multicast interface: local address (IPv4) or name (IPv6)\n"
    "      --teletext-caption <t> page caption (default: UNDERTHEC)\n"
    "  -n, --castle-name <text>   text on the castle, max 11 chars\n"
    "      --no-castle            disable the castle\n"
    "  -h, --help                 this help\n"
    "  -v, --version              show version\n\n"
    "keys while running:\n"
    "  q quit, r redraw, p/space pause, t toggle transparency, f feed, s settings, h help\n"
#ifdef __DJGPP__
    "  v cycle text modes\n"
#endif
    "\n"
    "environment variables:\n"
    "  UNDERTHEC_FISH=auto|number          like -a's fish=\n"
    "  UNDERTHEC_AQUATIC_LIFE=<def>        like -a, except for fish=\n"
    "  UNDERTHEC_CLASSIC=1.0|1.1           like -c\n"
    "  UNDERTHEC_MESSAGE=<text>            like -m\n"
    "  UNDERTHEC_MESSAGE_COLOR=<color>     like -M\n"
    "  UNDERTHEC_MESSAGE_POSITION=<pos>    like -P\n"
    "  UNDERTHEC_PACE=<pace>               like -p\n"
    "  UNDERTHEC_FPS=<N>                   like -f\n"
    "  UNDERTHEC_SCREENSAVER=0|1           like -s\n"
    "  UNDERTHEC_UTURN_CHANCE=<N>          like -u\n"
    "  UNDERTHEC_COLORS=<1|1-*|2|2-*|7|16> like -C\n"
    "  UNDERTHEC_TRANSPARENT=0|1           like -t\n"
    "  UNDERTHEC_TELETEXT=t42|ts           like --teletext\n"
    "  UNDERTHEC_TELETEXT_MODE=text|mosaic like --teletext-mode\n"
    "  UNDERTHEC_MCAST=<GROUP:PORT>        like --mcast\n"
    "  UNDERTHEC_MCAST_TTL=<N>             like --ttl\n"
    "  UNDERTHEC_MCAST_IFACE=<if>          like --iface\n"
    "  UNDERTHEC_TELETEXT_CAPTION=<text>   like --teletext-caption\n"
    "  UNDERTHEC_CASTLE_NAME=<text>        like --castle-name\n"
    "  UNDERTHEC_NO_CASTLE=0|1             like --no-castle\n",
    stdout);
}
